---
driver:
  name: docker
  use_sudo: false
  privileged: true
  hostname: kitchen

provisioner:
  name: chef_zero
  require_chef_omnibus: true
  client_rb:
    node_name: zero-client
    client_key: /tmp/kitchen/clients/zero-client.pem

platforms:
  - name: centos-7
  - name: centos-6
  - name: ubuntu-16.04
  - name: ubuntu-14.04
  - name: debian-8
  - name: debian-7

suites:
  - name: default
    run_list:
      - recipe[rotate-passwords-test]
    attributes:
