---
driver:
  name: docker

provisioner:
  name: chef_zero
  require_chef_omnibus: true
  client_rb:
    node_name: zero-client
    client_key: /tmp/kitchen/clients/zero-client.pem

platforms:
  - name: centos-7
    driver_config:
      provision_command:
      run_command: /usr/sbin/init
      privileged: true
      hostname: kitchen

suites:
  - name: default
    run_list:
      - recipe[rotate-passwords-test]
    attributes:
